### ISSUE TITLE
ActiveRecord adapter requires database connection during asset precompilation

### ISSUE THREAD

**Issue by luopio** [attr-encrypted/attr_encrypted#171]
I integrated attr_encrypted to an existing project and all went smoothly until I tried a docker build. I have `rake asset:precompile` in my Dockerfile, which causes the underlying error. My solution for it is also listed below, but I thought it might be a good idea to submit this ticket if you think this might be something worth fixing.

```
Step 20 : RUN mkdir -p /usr/src/app/log &&     chmod -R 775 /usr/src/app/log &&     rake assets:precompile
 ---> Running in 5ecacaa0d0be
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/connection_handling.rb:87:in `connection'
/usr/local/bundle/gems/activerecord-4.2.3/lib/active_record/model_schema.rb:230:in `table_exists?'
/usr/local/bundle/gems/attr_encrypted-1.3.4/lib/attr_encrypted/adapters/active_record.rb:59:in `attribute_instance_methods_as_symbols'
/usr/local/bundle/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:130:in `block in attr_encrypted'
/usr/local/bundle/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:125:in `each'
/usr/local/bundle/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:125:in `attr_encrypted'
/usr/local/bundle/gems/attr_encrypted-1.3.4/lib/attr_encrypted/adapters/active_record.rb:51:in `attr_encrypted'
/usr/local/bundle/bundler/gems/lifelife_core-b49b249d8e51/app/models/lifelife_core/users/tenant_profile.rb:13:in `<class:TenantProfile>'
/usr/local/bundle/bundler/gems/lifelife_core-b49b249d8e51/app/models/lifelife_core/users/tenant_profile.rb:8:in `<module:Users>'
/usr/local/bundle/bundler/gems/lifelife_core-b49b249d8e51/app/models/lifelife_core/users/tenant_profile.rb:6:in `<module:LifelifeCore>'
/usr/local/bundle/bundler/gems/lifelife_core-b49b249d8e51/app/models/lifelife_core/users/tenant_profile.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/src/app/app/admin/tenant_profile.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:209:in `block in load'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/error.rb:41:in `capture'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:209:in `load'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:201:in `block in load!'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:201:in `each'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:201:in `load!'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin/application.rb:223:in `routes'
/usr/local/bundle/bundler/gems/activeadmin-a5a53c3f2b8f/lib/active_admin.rb:79:in `routes'
/usr/src/app/config/routes.rb:4:in `block in <top (required)>'
/usr/local/bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
/usr/local/bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
/usr/local/bundle/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:412:in `draw'
/usr/src/app/config/routes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `call'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `execute'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `public_send'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/railtie.rb:194:in `method_missing'
/usr/src/app/config/environment.rb:9:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

The solution I am using to overcome the missing database connection is `activerecord-nulldb-adapter`. The main idea is nicely described here: http://blog.zeit.io/use-a-fake-db-adapter-to-play-nice-with-rails-assets-precompilation/

**Comment by saghaulor** [comment]
@luopio I believe that this issue was resolved with https://github.com/attr-encrypted/attr_encrypted/pull/160. Please feel free to reopen this issue if it did not address your problem.

**Comment by luopio** [comment]
Thanks for the support @saghaulor. I've learned since that you can't really have asset compilation in the Dockerfile since rake wants to initialize the Rails app, which will require a database connection. So the issue wasn't with attr_encrypted to begin with.

**Comment by wflanagan** [comment]
Is there any chance of revisiting this? 

I'd say that modern practice these day IS to do asset pre-compilation in the build phase of your image. And, this image will likely NOT have database access. I have been able to get around pretty much every other problem.. but attr-encrypted won't take a dummy database-url and required a full connection (meaning that you have to not only have a url, but a connection, and migrated database).
