### ISSUE TITLE
When Using a Method for a Key, the Method has to Be Public

### ISSUE THREAD

**Issue by stephenreid** [attr-encrypted/attr_encrypted#242]
When I specify that they key for a field is a method (through a symbol) and have that method either private or protected, saving the object results in this error

```
oMethodError: undefined method `bytesize' for :encryption_key:Symbol
/.rvm/gems/ruby-2.1.7/gems/encryptor-3.0.0/lib/encryptor.rb:60:in `crypt'
/.rvm/gems/ruby-2.1.7/gems/encryptor-3.0.0/lib/encryptor.rb:36:in `encrypt'
/.rvm/gems/ruby-2.1.7/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:259:in `encrypt'
/.rvm/gems/ruby-2.1.7/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:337:in `encrypt'
/.rvm/gems/ruby-2.1.7/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:159:in `block (2 levels) in attr_encrypted'
/.rvm/gems/ruby-2.1.7/gems/attr_encrypted-3.0.3/lib/attr_encrypted/adapters/active_record.rb:76:in `block in attr_encrypted'
```

**Comment by saghaulor** [comment]
Thank you for reporting this @stephenreid 

It's good practice to keep the key protected/private. A fix is on the way. However, I'm not ready to push a new gem version just yet.
