### ISSUE TITLE
NoMethodError: undefined method `authenticated?' for OpenSSL::Cipher on JRuby

### ISSUE THREAD

**Issue by ChrisSandison** [attr-encrypted/attr_encrypted#244]
Ran into this error running `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.102-b14 on 1.8.0_102-8u102-b14.1-1~bpo8+1-b14 +jit [linux-x86_64]`

When I print the available methods for the cipher for this algorithm in jruby I get a completely different set than the ones if I just check using irb.

Backtrace:

```
NoMethodError (undefined method `authenticated?' for #<OpenSSL::Cipher:0x2db88592>):
unity_1   |   encryptor (3.0.0) lib/encryptor.rb:86:in `crypt'
unity_1   |   encryptor (3.0.0) lib/encryptor.rb:36:in `encrypt'
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted.rb:259:in `encrypt'
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted.rb:337:in `encrypt'
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted.rb:159:in `block in gs_client_secrets='
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted/adapters/active_record.rb:76:in `block in gs_client_secrets_with_dirtiness='
unity_1   |   org/jruby/RubyKernel.java:1812:in `public_send'
unity_1   |   activerecord (4.2.4) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
unity_1   |   activerecord (4.2.4) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
unity_1   |   org/jruby/RubyHash.java:1448:in `each'
unity_1   |   activerecord (4.2.4) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted/adapters/active_record.rb:29:in `perform_attribute_assignment'
unity_1   |   attr_encrypted (3.0.3) lib/attr_encrypted/adapters/active_record.rb:36:in `assign_attributes'
unity_1   |   devise (4.2.0) lib/devise/models/database_authenticatable.rb:71:in `update_with_password'
unity_1   |   devise (4.2.0controllers) devise/registrations_controller.rb:94:in `update_resource'
...
```

**Comment by saghaulor** [comment]
Are you using the jruby-openssl gem? I'm not well versed in JRuby.

Encryptor is a wrapper around MRIs openssl standard library. It supports a method called `authenticated?`

As I understand it, the jruby-openssl gem provides the same interface as MRIs openssl stdlib.

https://github.com/jruby/jruby-openssl/blob/44582592eda3337e095742f99ebc1fc737f536d9/src/main/java/org/jruby/ext/openssl/Cipher.java#L1310
