### ISSUE TITLE
Not working with Rails 4 (.2.7.1)? ArgumentError: wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by lichtamberg** [attr-encrypted/attr_encrypted#246]
It appears that this gem is not working with Rails 4?
```shell
class MyModel < ActiveRecord::Base
    attr_encrypted :test, key: "test"
end

MyModel.create!(test: "1234")

ArgumentError: wrong number of arguments (2 for 1)
from /Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
```

When I trace it down, i get the following backtrace:

```shell
wrong number of arguments (2 for 1)
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
/Users/user/.rvm/gems/ruby-2.2.6/gems/attr_encrypted-3.0.1/lib/attr_encrypted/adapters/active_record.rb:27:in `perform_attribute_assignment'
/Users/user/.rvm/gems/ruby-2.2.6/gems/attr_encrypted-3.0.1/lib/attr_encrypted/adapters/active_record.rb:34:in `assign_attributes_with_attr_encrypted'
/Users/user/.rvm/gems/ruby-2.2.6/gems/protected_attributes-1.0.9/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/core.rb:281:in `initialize'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/inheritance.rb:61:in `new'
/Users/user/.rvm/gems/ruby-2.2.6/gems/protected_attributes-1.0.9/lib/active_record/mass_assignment_security/validations.rb:15:in `create!'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1029:in `record_version_state_after_migrating'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:999:in `block in execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1044:in `ddl_transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/user/.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
ArgumentError: wrong number of arguments (2 for 1)
```

**Comment by lichtamberg** [comment]
It looks like this error really happens only for rails > 4, because the rails method's signature of assign_attributes has changed:

```ruby
# /.rvm/gems/ruby-2.2.6/gems/activerecord-4.2.7.1/lib/active_record/attribute_assignment.rb
    def assign_attributes(new_attributes)

# /.rvm/gems/ruby-2.2.6/gems/activerecord-3.2.22.5/lib/active_record/attribute_assignment.rb
def assign_attributes(new_attributes, options = {})
```

**Comment by lichtamberg** [comment]
I've added a pull request, would be great if you could take a look at it.

**Comment by saghaulor** [comment]
@lichtamberg This gem definitely works with Rails 4+. Please see the build matrix of the last build https://travis-ci.org/attr-encrypted/attr_encrypted/builds/174329129, you'll notice there's a build for 4.2 and for 5.0.

**Comment by lichtamberg** [comment]
Hm, but then I dont understand why I get this error message... If you could take a look?

**Comment by lichtamberg** [comment]
Ah I see, I found the problem.

I am using the "protected_attributes" gem. After removing it, it works fine.
But anyway, I need this gem since I cannot upgrade everything at the same time...

**Comment by lichtamberg** [comment]
I didn't found a solution to make it work with the protected_attributes gem.
I removed it now completely and it works fine now.
