### ISSUE TITLE
ArgumentError: must specify an iv - But not problems on Rails console

### ISSUE THREAD

**Issue by josegrad** [attr-encrypted/attr_encrypted#277]
Hi,

I'm on Rails 5.0.0 and Ruby 2.2.2. I use Mongoid.

I have this class:

```
class Shipment
    extend AttrEncrypted
    field :encrypted_details, :type => String
    attr_encrypted :details, :key => ENV['WRK'], :encode => true, :charset => "utf-8"
end
```

ENV['WRK'] is key like "a847900d1.....087a3935e9"

```
ENV['WRK'].size
 => 128 
```

From Rails console I can do:
```
s = Shipment.create(:details => {"some" => "hash"})

2.2.2 :051 > s.encrypted_details
 => "ODtF83r9FaPgKXaGqoPaRS1G//j3MSP8arhJ4sTi5s0=\n" 
2.2.2 :050 > s.details
 => {"some"=>"hash"} 

```

s.details returns the decrypted details as expected.

However, if I create that shipment from a controller...

```
Shipment.create(:details => {"another" => "hash"})

s = Shipment.last
2.2.2 :061 >   s.encrypted_details
 => "hy8Ye//NxINwjjrwIZihBsDtDmR4yQ==\n" 

2.2.2 :059 >   s.details
ArgumentError: must specify an iv
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/encryptor-3.0.0/lib/encryptor.rb:61:in `crypt'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:233:in `decrypt'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:317:in `decrypt'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:155:in `block (2 levels) in attr_encrypted'
	from (irb):59
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/josegranado/.rvm/gems/ruby-2.2.2@rails5.0.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

It works fine from the console, why not from the controller?
Any hints?

**Comment by josegrad** [comment]
18 days gone...
Any comments on this one?

**Comment by kubaaa** [comment]
Hi @josegrad . You need  add field to your Shipment
`field :encrypted_details_iv, :type => String`

**Comment by PilotCurly99** [comment]
I ran into this issue while developing.  Removed fields from database and added them again, but I also reloaded the model in the session I was working on.  Worked 4.0 after I did those three things.  I suspect it may have been the last one that actually fixed it.

**Comment by pvin** [comment]
Im also facing this is issue. Any solution?

**Comment by jancel** [comment]
Anyone figure out the fix/work-around?

**Comment by rubendinho** [comment]
I was intermittently getting this error when I had a non-"encrypted" version of the encrypted column in my db. Removing the column seems to have resolved the issue.

So if in addition to `encrypted_email` and `encrypted_email_iv`, you also have an `email` column, the `email` column (or more likely associated getting/setter methods) may be conflicting with some of the methods of this gem.

**Comment by easydatawarehousing** [comment]
This error can occur when a default value is set at the database level for the encrypted field.

**Comment by ibrahim-saifee** [comment]
I have found one very strange reason for this.
When you are adding this `attr_encrypted` to any DB table column, then the ActiveRecord::Model for that table should have a `name` column as well.
If you don't have the `name` column then try to add get and set methods for `name` in that model like this `attr_accessor :name`.
The example given in the gem https://github.com/attr-encrypted/attr_encrypted, also specifies the `:name` attribute.
It solved my problem, it's strange I am investigating it. Will update soon if I finds something.
