### ISSUE TITLE
Ruby 2.4.4 => `decode64': undefined method `unpack' for nil:NilClass 

### ISSUE THREAD

**Issue by mberrueta** [attr-encrypted/attr_encrypted#307]
Hello all, 
Im having an issue with ruby `2.4.4`

It was working without issues with `2.3.6`

```
ruby-2.4.4  ⬡ v8.4.0   develop ✔ 
$ RAILS_ENV=production rails c
/Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/base64.rb:59:in `decode64': undefined method `unpack' for nil:NilClass (NoMethodError)
	from /Users/mm/code/a-api/config/initializers/encryptor.rb:5:in `<top (required)>'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/notifications.rb:168:in `instrument'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/engine.rb:654:in `load_config_initializer'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/engine.rb:611:in `each'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:48:in `each'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
	from /Users/mm/code/a-api/config/environment.rb:5:in `<top (required)>'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/mm/.rvm/gems/ruby-2.4.4/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mm/.rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
    
```
    
 ```
    Encryptor.default_options.merge!(
      algorithm: 'xxxx',
      key: Base64.decode64(Rails.application.secrets.encrypt_secret_key),
      iv: Base64.decode64(Rails.application.secrets.encrypt_iv),
      salt: Base64.decode64(Rails.application.secrets.encrypt_salt)
    )
```

Any Idea?

**Comment by meshpi** [comment]
Are you sure your `secrets.yml` is there with the expected configuration?

I imagine you're testing a new ruby version with a new clone of your repo which shouldn't include secrets. Sometimes switching branches gets rid of secrets too.

`decode64` expects a string, and calls `.unpack` on that string.

**Comment by mberrueta** [comment]
yeah, you right, something wrong with my secrets.yml.

thanks man!
