### ISSUE TITLE
Can't modify frozen String

### ISSUE THREAD

**Issue by MiralDesai** [attr-encrypted/attr_encrypted#312]
I seem to be getting this a lot, and the backtrace points to the error being inside attr_encrypted (I'm using version 3.0.0).

For context, I have a user model, with a encrypted field (message). The encryption all works great. However when I call that field I get the error in the title, `user.message.present?` for example. This fails in `rails console` too, if that helps. Very strange behaviour because `user.message` returns just fine.

```
"/Users/<>/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:238:in `force_encoding'",
      "/Users/<>/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:238:in `decrypt'",
      "/Users/<>/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:317:in `decrypt'",
      "/Users/<>/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/attr_encrypted-3.0.3/lib/attr_encrypted.rb:155:in `block (2 levels) in attr_encrypted'"
```

Any ideas?

**Comment by chadwilken** [comment]
I would imagine your model has the magic comment `frozen_string_literal: true`? I am guessing this because `force_encoding` changes the string instead of making a copy of the string and making the changes on the copy.

**Comment by MiralDesai** [comment]
Yeah I've got the `frozen_string_literal` comment at the top of my model

**Comment by chadwilken** [comment]
You either need to remove that for the time being or fork this and make a patch so it uses a copy and not the original. Their code reassigns the value anyways so I think that is what they intended to happen but it isn't.

**Comment by MiralDesai** [comment]
Makes sense, have removed the magic comment for now and excluded it from rubocop but obviously not ideal. I'll see what I can do about a PR to at least get a fix rolling over the weekend.

**Comment by MiralDesai** [comment]
According to this https://stackoverflow.com/a/21614613/565672

force_encoding does not change the string itself. It's blowing up here, but it shouldn't?

The issue also persists even after removing our magic comment
