### ISSUE TITLE
Experiencing multiple issues with decryption in production app

### ISSUE THREAD

**Issue by amrocco** [attr-encrypted/attr_encrypted#323]
I am running into some issues with decryption in my application. Our exception notifier is reporting: `must specify an iv` with the backtrace:
`/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/encryptor-3.0.0/lib/encryptor.rb:61:in `crypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:240:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:329:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'
(eval):16:in `block in compile_source'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/to_hash.rb:43:in `instance_exec'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/to_hash.rb:43:in `visit_Code'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/visitor.rb:14:in `dispatch'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/visitor.rb:4:in `visit'`

And also another exception with no message, with the backtrace:
`/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `final'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `crypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:240:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:329:in `decrypt'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'
(eval):16:in `block in compile_source'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/to_hash.rb:43:in `instance_exec'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/to_hash.rb:43:in `visit_Code'
/home/ubuntu/.../current/vendor/bundle/ruby/2.5.0/gems/rabl-rails-0.4.3/lib/rabl-rails/visitors/visitor.rb:14:in `dispatch'`

If I go into the rails console and try to decrypt all of the objects that are throwing these errors they decrypt without issue, however we're getting these exceptions every 30-40 minutes in our production app (so not every time the specific call is made).

Using rails 5.1.6, ruby 2.5.1, and attr_encrypted 3.1.0

**Comment by amrocco** [comment]
This sounds very similar to what is being mentioned here: https://github.com/attr-encrypted/attr_encrypted/pull/320
