### ISSUE TITLE
I got an issue with encryptor running locally on MacOS Mojave

### ISSUE THREAD

**Issue by g3ortega** [attr-encrypted/attr_encrypted#352]
I'm getting this issue while trying to access some encrypted attributes locally: 

```
OpenSSL::Cipher::CipherError - :
  encryptor (3.0.0) lib/encryptor.rb:98:in `crypt'
  encryptor (3.0.0) lib/encryptor.rb:49:in `decrypt'
  attr_encrypted (3.1.0) lib/attr_encrypted.rb:240:in `decrypt'
  attr_encrypted (3.1.0) lib/attr_encrypted.rb:329:in `decrypt'
  attr_encrypted (3.1.0) lib/attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'

```

I even uninstalled `rbenv` and tried `rvm` with OpenSSL path set manually for during Ruby compilation -just in case- but I'm still getting the same error.

**Comment by g3ortega** [comment]
I copy the secret key base from staging, and it worked!
