### ISSUE TITLE
Is not compatible with the latest rails changes

### ISSUE THREAD

**Issue by fatkodima** [attr-encrypted/attr_encrypted#456]
Rails 7.2.0.beta3 will be released soon, and if you try to point rails at `7-2-stable` branch, you will get an error:
```
NoMethodError:
 undefined method `define_attribute_method_pattern' for class ApiKey
 gems/rails-671e853bc193/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
 gems/attr_encrypted-4.1.0/lib/attr_encrypted.rb:308:in `method_missing'
 gems/attr_encrypted-4.1.0/lib/attr_encrypted/adapters/active_record.rb:142:in `method_missing_with_attr_encrypted'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:94:in `alias_attribute_method_definition'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:82:in `block in generate_alias_attribute_methods'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:81:in `each'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:81:in `generate_alias_attribute_methods'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:134:in `block (3 levels) in generate_alias_attributes'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:133:in `each'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:133:in `block (2 levels) in generate_alias_attributes'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:132:in `each'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:132:in `block in generate_alias_attributes'
 gems/activesupport-7.2.0.beta2/lib/active_support/code_generator.rb:41:in `batch'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:131:in `generate_alias_attributes'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:121:in `block in define_attribute_methods'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:108:in `synchronize'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods.rb:108:in `define_attribute_methods'
 gems/rails-671e853bc193/activerecord/lib/active_record/core.rb:789:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/persistence.rb:817:in `init_internals'
 gems/activemodel-7.2.0.beta2/lib/active_model/dirty.rb:366:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/attribute_methods/dirty.rb:197:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/timestamp.rb:103:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/associations.rb:76:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/autosave_association.rb:279:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/transactions.rb:434:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/touch_later.rb:50:in `init_internals'
 gems/rails-671e853bc193/activerecord/lib/active_record/core.rb:455:in `initialize'
 gems/rails-671e853bc193/activerecord/lib/active_record/inheritance.rb:76:in `new'
 gems/rails-671e853bc193/activerecord/lib/active_record/inheritance.rb:76:in `new'
....
```

**Comment by fatkodima** [comment]
Sorry, false positive, it was a problem in our code.
